In [58]:
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import joblib
from matplotlib.colors import ListedColormap

plt.style.use('fivethirtyeight')

In [59]:
class Perceptron:
    def __init__(self,eta:float=None, epochs:int=None):
        self.weights = np.random.randn(3) * 1e-4 # small random weights
        training = (eta is not None) and (epochs is not None)
        if training:
            print(f'initial weights before training : \n{self.weights}')
        self.eta = eta
        self.epochs = epochs
        
        
    def _z_outcome(self,inputs,weights):
        return np.dot(inputs,weights)
    
    
    def activation_function(self,z):
        return np.where(z>0,1,0)
    
   
    def fit(self,X,y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f'X with bias: \n{X_with_bias}')
        
        for epoch in range(self.epochs):
            print(f'for epoch >> {epoch}')
            print("---"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f'predicted value after forward pass: \n{y_hat}')
            
            self.error = self.y - y_hat
            print(f'error: \n{self.error}')
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f'updated weights after epoch: {epoch+1}/{self.epochs}: \n{self.weights}')
            print("##"*10)
     
    
    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias,self.weights)
        return self.activation_function(z)
    
    
    def total_loss(self):
        total_loss = np.sum(self.error)
        print(f'total loss: {total_loss}\n')
        return total_loss
    
    
    def _create_dir_return_path(self,model_dir,filename):
        os.makedirs(model_dir, exist_ok=True)
        return os.path.join(model_dir,filename)
    
    
    def save(self,filename, model_dir=None):
        if model_dir is not None:
            model_file_path = self._create_dir_return_path(model_dir,filename)
            joblib.dump(self, model_file_path)
        else:
            model_file_path = self._create_dir_return_path("model",filename)
            joblib.dump(self, model_file_path)
            
            
    def load(self,filepath):
        return joblib.load(filepath)

In [60]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y":  [0,0,0,1]
}

df_AND = pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [61]:
def prepare_data(df,target_col="y"):
    X = df.drop("y",axis=1)
    
    y = df["y"]
    
    return X,y

In [62]:
X,y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10
model_and = Perceptron(eta=ETA, epochs=EPOCHS)
model_and.fit(X,y)

_ = model_and.total_loss()

initial weights before training : 
[9.25103994e-05 1.13560925e-04 8.43204657e-05]
X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch >> 0
------------------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-0.09990749 -0.09988644  0.20008432]
####################
for epoch >> 1
------------------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[9.25103994e-05 1.13560925e-04 1.00084320e-01]
####################
for epoch >> 2
------------------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[1.00092510e-01 1.00113561e-01 8.43204657e-05]
####################
for epoch >> 3
------------------------------
predicted value after forward pass: 
[0 1

In [63]:
model_and.save(filename="and.model")

In [64]:
reload_and = Perceptron().load(filepath="model/and.model")

In [67]:
reload_and.predict(X=[[1,1]])

array([1])

In [68]:
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y":  [0,1,1,1]
}

df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [69]:
def prepare_data(df,target_col="y"):
    X = df.drop("y",axis=1)
    
    y = df["y"]
    
    return X,y

In [70]:
X,y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10
model_or = Perceptron(eta=ETA, epochs=EPOCHS)
model_or.fit(X,y)

_ = model_or.total_loss()

initial weights before training : 
[5.37796587e-05 3.61768436e-06 9.51542639e-05]
X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch >> 0
------------------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.20005378  0.20000362 -0.29990485]
####################
for epoch >> 1
------------------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.20005378  0.20000362 -0.19990485]
####################
for epoch >> 2
------------------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 0.20005378  0.20000362 -0.09990485]
####################
for epoch >> 3
------------------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   

In [71]:
model_or.save(filename="or.model")

In [72]:
reload_or = Perceptron().load(filepath="model/or.model")

In [73]:
reload_and.predict(X=[[1,1]])

array([1])

In [49]:
XOR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y":  [0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)
df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [53]:
def prepare_data(df,target_col="y"):
    X = df.drop("y",axis=1)
    
    y = df["y"]
    
    return X,y

In [54]:
X,y = prepare_data(df_XOR)

ETA = 0.1
EPOCHS = 10
model_xor = Perceptron(eta=ETA, epochs=EPOCHS)
model_xor.fit(X,y)

_ = model_xor.total_loss()

initial weights before training : 
[-1.19523018e-04  2.14405010e-05 -1.05775353e-04]
X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch >> 0
------------------------------
predicted value after forward pass: 
[1 1 0 1]
error: 
0   -1
1    0
2    1
3   -1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-0.00011952 -0.09997856  0.09989422]
####################
for epoch >> 1
------------------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 9.98804770e-02  2.14405010e-05 -1.00105775e-01]
####################
for epoch >> 2
------------------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[-0.00011952 -0.09997856  0.09989422]
####################
for epoch >> 3
------------------------------
predicted value after forward pass: 
[0 0 0 